[versions]
agp = "8.5.2"
kotlin = "1.9.24"
junit = "4.13.2"
desugarJdkLibs = "2.0.4"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
